# Generated by Django 5.0.2 on 2024-04-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0009_customuser_etablissement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
