# Generated by Django 5.0.2 on 2024-05-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0011_commande'),
        ('galsen', '0011_notification'),
    ]

    operations = [
    ]
