# Generated by Django 5.0.2 on 2024-05-04 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0012_merge_0011_commande_0011_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='job',
            name='dispostule',
            field=models.ManyToManyField(blank=True, related_name='dispostule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='postule_job',
            field=models.ManyToManyField(blank=True, related_name='postule', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='shared_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='langue',
            field=models.CharField(choices=[('français', 'Français'), ('anglais', 'Anglais'), ('spagnol', 'Spagnol'), ('italien', 'Italien'), ('arabe', 'Arabe')], default='français', max_length=255),
        ),
        migrations.DeleteModel(
            name='Postule',
        ),
    ]
