# Generated by Django 5.0.2 on 2024-05-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0013_remove_post_categories_job_dispostule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
