# Generated by Django 5.0.2 on 2024-05-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0014_delete_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(default=1, upload_to='cover_images/'),
            preserve_default=False,
        ),
    ]
