# Generated by Django 5.0.2 on 2024-05-20 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0015_product_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover',
        ),
    ]
