# Generated by Django 5.0.2 on 2024-06-01 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0016_remove_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commande_product',
            field=models.ManyToManyField(blank=True, related_name='commande', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='no_commande',
            field=models.ManyToManyField(blank=True, related_name='no_commande', to=settings.AUTH_USER_MODEL),
        ),
    ]
