# Generated by Django 5.0.2 on 2024-06-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0019_delete_suivi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abonnement',
        ),
    ]
