# Generated by Django 5.0.2 on 2024-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0021_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='commande_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_commande',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='langue',
            field=models.CharField(choices=[('français', 'Français'), ('anglais', 'Anglais'), ('spagnol', 'Espagnol'), ('italien', 'Italien'), ('arabe', 'Arabe')], default='français', max_length=255),
        ),
    ]
