# Generated by Django 5.0.2 on 2024-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0023_commande_reponsecommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
