# Generated by Django 5.0.2 on 2024-06-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0024_alter_commande_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande',
            field=models.CharField(max_length=255),
        ),
    ]
