# Generated by Django 5.0.2 on 2024-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0025_alter_commande_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='precision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
