# Generated by Django 5.0.1 on 2024-11-13 13:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0030_annonce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponse',
            old_name='date_creation',
            new_name='date_creation_annonce',
        ),
        migrations.AddField(
            model_name='annonce',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
