# Generated by Django 5.0.1 on 2024-11-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0034_alter_annonce_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
