# Generated by Django 5.0.1 on 2024-11-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0035_alter_annonce_prix_alter_product_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_images/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner_images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('number_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('number_whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('number_telegram', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
