# Generated by Django 5.0.1 on 2024-11-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galsen', '0036_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='situation_matrimoniale',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('fiance', 'Fiancé(e)'), ('divorce', 'Divorcé(e)'), ('couple', 'En couple')], default='celibataire', max_length=20),
        ),
    ]
